import mongoose from "mongoose";
import Template from "../src/models/Template.model.js";
import dotenv from "dotenv";

dotenv.config();

// --- THE JAKE GUTIERREZ TEMPLATE (Adapted for your current generator) ---
const jakeGutierrezLatex = `\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{} 
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

% --- CUSTOM COMMANDS ---
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

% NOTE: Added \\small here so standard \\items generated by your backend look correct
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}\\small} 
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

% --- HEADING ---
\\begin{center}
    \\textbf{\\Huge \\scshape {{PERSONAL.NAME}}} \\\\ \\vspace{1pt}
    \\small {{PERSONAL.LOCATION}} 
    {{#IF_PHONE}} $|$ {{PERSONAL.PHONE}} {{/IF_PHONE}}
    {{#IF_EMAIL}} $|$ \\href{mailto:{{PERSONAL.EMAIL}}}{{{PERSONAL.EMAIL}}} {{/IF_EMAIL}}
    \\\\[3pt]
    {{#IF_LINKEDIN}}
    \\href{https://{{PERSONAL.LINKEDIN}}}{\\underline{LinkedIn}} $|$ 
    {{/IF_LINKEDIN}}
    {{#IF_GITHUB}}
    \\href{https://{{PERSONAL.GITHUB}}}{\\underline{Github}} 
    {{/IF_GITHUB}}
    {{#IF_WEBSITE}}
    $|$ \\href{https://{{PERSONAL.WEBSITE}}}{\\underline{Portfolio}}
    {{/IF_WEBSITE}}
\\end{center}


% --- EDUCATION ---
{{#IF_EDUCATION}}
\\section{Education}
  \\resumeSubHeadingListStart
    {{#EDUCATION}}
    \\resumeSubheading
      {{{INSTITUTION}}}{{{LOCATION}}}
      {{{DEGREE}}}{{{START_DATE}} -- {{END_DATE}}}
      % If you want to show GPA or Coursework, uncomment below:
      % \\resumeItemListStart
      %   {{#IF_GPA}}\\item GPA: {{GPA}}{{/IF_GPA}}
      % \\resumeItemListEnd
    {{/EDUCATION}}
  \\resumeSubHeadingListEnd
{{/IF_EDUCATION}}


% --- SKILLS ---
{{#IF_SKILLS}}
\\section{Technical Skills}
\\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     {{#IF_LANGUAGES}} \\textbf{Languages:} {{LANGUAGES}} \\\\ {{/IF_LANGUAGES}}
     {{#IF_TECHNOLOGIES}} \\textbf{Technologies:} {{TECHNOLOGIES}} \\\\ {{/IF_TECHNOLOGIES}}
    }}
\\end{itemize}
{{/IF_SKILLS}}


% --- EXPERIENCE ---
{{#IF_EXPERIENCE}}
\\section{Experience}
  \\resumeSubHeadingListStart
    {{#EXPERIENCE}}
    \\resumeSubheading
      {{{POSITION}}}{{{START_DATE}} -- {{END_DATE}}}
      {{{COMPANY}}}{{{LOCATION}}}
      \\resumeItemListStart
        {{#HIGHLIGHTS}}
        {{.}}
        {{/HIGHLIGHTS}}
      \\resumeItemListEnd
    {{/EXPERIENCE}}
  \\resumeSubHeadingListEnd
{{/IF_EXPERIENCE}}


% --- PROJECTS ---
{{#IF_PROJECTS}}
\\section{Recent Projects}
    \\resumeSubHeadingListStart
      {{#PROJECTS}}
      \\resumeProjectHeading
          {\\textbf{{{NAME}}} {{#IF_TECHNOLOGIES}}$|$ \\emph{{{TECHNOLOGIES}}}{{/IF_TECHNOLOGIES}}}{{{DATE}}}
          \\resumeItemListStart
            {{#HIGHLIGHTS}}
            {{.}}
            {{/HIGHLIGHTS}}
            {{#IF_LINK}}\\item \\href{{{LINK}}}{\\underline{Project Link}}{{/IF_LINK}}
          \\resumeItemListEnd
      {{/PROJECTS}}
    \\resumeSubHeadingListEnd
{{/IF_PROJECTS}}

\\end{document}`;

const updateTemplate = async () => {
  try {
    // Replace with your actual Mongo URI or ensure env var is set
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    // The slug you want to update or create
    const slug = "jake-gutierrez"; 

    const filter = { slug: slug };
    const update = {
      name: "Modern Professional (Jake Gutierrez)",
      description: "Clean, ATS-friendly resume template. Popular single-column design.",
      latexTemplate: jakeGutierrezLatex, // The new LaTeX string
      isActive: true,
      // Ensure required fields map to what your frontend expects
      requiredFields: {
          personal: ['name', 'email', 'phone', 'linkedin', 'github'],
          education: ['institution', 'location', 'degree', 'startDate', 'endDate'],
          experience: ['company', 'position', 'location', 'startDate', 'endDate', 'highlights'],
          projects: ['name', 'technologies', 'highlights'],
          skills: ['languages', 'technologies']
      }
    };

    // upsert: true means "Create if it doesn't exist, Update if it does"
    const result = await Template.findOneAndUpdate(filter, update, { 
      new: true, 
      upsert: true,
      setDefaultsOnInsert: true 
    });

    console.log(`✅ Template '${result.name}' updated successfully!`);
    console.log(`ID: ${result._id}`);
    
    process.exit(0);
  } catch (error) {
    console.error("❌ Error updating template:", error);
    process.exit(1);
  }
};

updateTemplate();